# Use the official Cypress base image
FROM cypress/included:13.6.3

WORKDIR /e2e

COPY cypress/ /e2e/cypress/
COPY cypress.config.js /e2e/
COPY package.json /e2e/
COPY package-lock.json /e2e/

# Install NPM dependencies, avoid running post-install scripts
RUN npm ci --ignore-scripts

# Verify Cypress has been installed correctly.
RUN npx cypress verify

# Command to run tests
CMD ["npx", "cypress", "run"]
